name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-docker-build.yaml@master
    with:
      runners: docker-dns-runners
      image: docker-dns
  deploy:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-flux-deploy.yaml@master
    secrets: inherit
    needs: docker-build-push
    with:
      runners: docker-dns-runners
      old-image: container-registry.k8s.home.blrobinson.uk/docker-dns
      deploy-image: ${{ needs.docker-build-push.outputs.tags }}
      flux-file: clusters/home/dns/deployment.yaml
  monitor-deploy:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-wait-for-deploy.yaml@master
    needs: deploy
    with:
      runners: docker-dns-runners
      namespace: dns
      kustomization: dns
      deployment-name: dns
      flux-sha: ${{ needs.deploy.outputs.deploy-sha }}
      timeout: 1m
  revert:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-flux-deploy.yaml@master
    if: ${{ always() && needs.monitor-deploy.result == 'failure' }}
    secrets: inherit
    needs:
      - deploy
      - monitor-deploy
    with:
      runners: docker-dns-runners
      revert: true
      revert-sha: ${{ needs.deploy.outputs.deploy-sha }}
  monitor-revert:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-wait-for-deploy.yaml@master
    needs: revert
    if: ${{ always() && needs.revert.result == 'success' }}
    with:
      runners: docker-dns-runners
      namespace: dns
      kustomization: dns
      deployment-name: dns
      flux-sha: ${{ needs.revert.outputs.deploy-sha }}
