name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    runs-on: docker-dns-runners
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: |
            container-registry.k8s.home.blrobinson.uk/docker-dns
          tags: |
            type=sha
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
      - uses: azure/setup-kubectl@v3
      - name: Start Rollout restart
        run: kubectl rollout restart deployment/dns -n dns
      - name: Monitor restart
        run: kubectl rollout status deployment/dns -n dns