name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-docker-build.yaml@master
    with:
      runners: docker-dns-runners
      image: docker-dns
  deploy:
    runs-on: docker-dns-runners
    needs: docker-build-push
    steps:
    - uses: azure/setup-kubectl@v3
    - name: Start Rollout restart
      run: kubectl rollout restart deployment/dns -n dns
    - name: Monitor restart
      run: kubectl rollout status deployment/dns -n dns
